close all;
clear all;
clc;
t=0:0.1:10;
x=2*t;
subplot(2 ,2 ,1);
plot(t,x);
xlabel('time');
ylabel('amplitude');
title('straight line');
grid on;
y=3*t+5;
subplot(2,2,2);
plot(t,y);
xlabel('time');
ylabel('amplitude');
title('straight line2');
grid on;
z=4*t;
subplot(2 ,2, 3)
plot(t,z);
xlabel('time');
ylabel('amplitude');
title('straight line3');
grid on;
k=4*t+5;
subplot(2 ,2, 4);
plot(t,k);
xlabel('time');
ylabel('amplitude');
title('straight line4');
grid on;